title: generic-scratch3-make-block-parameters
hero_image: images/banner.png
description: generic-scratch3-make-block-parameters description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-06"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
