---
title: पॅरामीटर्ससह ब्लॉक बनवणे
hero_image: images/banner.png
description: पॅरामीटर्ससह ब्लॉक बनवणे
theme: लाल
duration: 0
listed: false
ingredient: true
copyedit: true
curriculum: बिल्डर, डिझाइन-0, प्रोग्रामिंग-१, भौतिक संगणन-0, उत्पादन-0, समुदाय-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: पॅरामीटर्ससह ब्लॉक बनवणे
