---
title: Criar um bloco com parâmetros
hero_image: images/banner.png
description: Criar um bloco com parâmetros
theme: vermelho #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: construtor, desenho-0, programação-2, phys-comp-0, fabricar-0, comunidade-0
interests: ""
technologies: "scratch"
site_areas:
steps:
  - 
    title: Criar um bloco com parâmetros
